### ISSUE TITLE
DjangoのSUが追加したものしか表示されない

### ISSUE THREAD

**Issue by mask337** [mask337/nanainfc#7]

**Comment by mask337** [comment]
pullし、SUアカウントを追加。
その後$python manage.py runserverを実行しlocalhost:8000/adminにてSUログインをしたときの様子。

画像の通り、追加したアカウント(mask~~)とuser01というアカウント(不明なドメインのアドレスのもの)が存在するのみで、以前追加したはずの2アカウントが表示されない。

改めてpullして確認してもらいたい。

<img width="1680" alt="スクリーンショット 2019-08-21 3 21 17" src="https://user-images.githubusercontent.com/16540634/63373802-7fb33200-c3c3-11e9-9fba-f8b86d0ad66e.png">

**Comment by mask337** [comment]
ちょっと強引な方法でuser01にログインしたところ、yukaというアカウントが前に存在して削除されているみたい、、、？？

<img width="951" alt="スクリーンショット 2019-08-21 3 40 32" src="https://user-images.githubusercontent.com/16540634/63374774-788d2380-c3c5-11e9-8534-0df51685c8d8.png">

**Comment by ktaka03a** [comment]
俺の方でkeitaだったものをadminなんちゃらとかいう名前に変えたあと、方針変更してそれとyukaを消してuser01を追加した
サーバー立ててそこで作業するようになるまで、user01をひとまず共有するアカウントにしてもいいんではなかろうか

**Comment by mask337** [comment]
なるほど、じゃああとでパスワード共有しますね
